// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("fredlock")>]
[<assembly: AssemblyProductAttribute("fredlock")>]
[<assembly: AssemblyDescriptionAttribute("An F# implementation of the redlock algorythm for distributed redis locks.")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "fredlock"
    let [<Literal>] AssemblyProduct = "fredlock"
    let [<Literal>] AssemblyDescription = "An F# implementation of the redlock algorythm for distributed redis locks."
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
